# Application-wide configuration
database:
  host: mariadb
  user: root
  database: 3t

redis:
  host: redis
  port: 6379
  db: 0
  streams:
    balance_updates: "balance:updated"

celery:
  schedules:
    update_balance: 30.0
    schedule_market_data_fetching: 30.0 # Runs every minute to check for needed updates

# Exchange and product configuration can be managed here
# or dynamically from the database.
market_data:
  timeframes:
    - "1m"
    - "4h"
  concurrency_limit: 10
