{
 "title": "3T Run Heath",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "symbol", "label": "symbol", "query": "select symbol from products" }
  ]
 },
 "panels": [
  {
   "title": "RUN RISK REMAINING",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`3t`",
     "rawSql": "SELECT\n  0.01379663161+(((latest_balance.account_value - take_profit.last_balance) / take_profit.last_balance)) AS percentage_change\nFROM\n  (\n    SELECT\n      account_value\n    FROM\n      balance_history\n    ORDER BY\n      timestamp DESC\n    LIMIT 1\n  ) AS latest_balance,\n  (\n    SELECT\n      last_balance\n    FROM\n      take_profit_state\n    ORDER BY\n      id DESC\n    LIMIT 1\n  ) AS take_profit;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`3t`",
     "rawSql": "SELECT\n  latest_balance.account_value AS current_balance,\n  take_profit.last_balance AS take_profit_balance,\n  ((latest_balance.account_value - take_profit.last_balance) / take_profit.last_balance) * 100 AS percentage_change\nFROM\n  (\n    SELECT\n      account_value\n    FROM\n      balance_history\n    ORDER BY\n      timestamp DESC\n    LIMIT 1\n  ) AS latest_balance,\n  (\n    SELECT\n      last_balance\n    FROM\n      take_profit_state\n    ORDER BY\n      id DESC\n    LIMIT 1\n  ) AS take_profit;"
    }
   ]
  },
  {
   "title": "Total Account Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, account_value FROM balance_history where $__timeFilter(timestamp) ORDER BY timestamp ASC"
    },
    {
     "dataset": "`3t`",
     "rawSql": "SELECT timestamp as time, cross_maintenance_margin_used FROM `3t`.balance_history  where $__timeFilter(timestamp) ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Runs Simulated P&L Health $symbol",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4.8, "x": 0, "y": 7 },
   "repeat": "symbol",
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "`3t`",
     "rawSql": "select start_time,live_pnl as 'active' from runs where end_time is null and exit_run = 0 and symbol in ($symbol) and height is null"
    },
    {
     "dataset": "`3t`",
     "rawSql": "select start_time,live_pnl as 'historical' from runs where symbol in ($symbol) and height is null"
    }
   ]
  },
  {
   "title": "Runs Position Direction $symbol",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4.8, "x": 0, "y": 17 },
   "repeat": "symbol",
   "targets": [
    {
     "dataset": "`3t`",
     "rawSql": "select start_time,sum(position_direction) as 'active' from runs where position_direction != 0 and exit_run = 0 and end_time is null and symbol in ($symbol) and height is null group by start_time"
    },
    {
     "dataset": "`3t`",
     "rawSql": "select start_time,sum(position_direction) as 'historical' from runs where position_direction != 0 and height is null group by start_time"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "`3t`",
     "rawSql": "select count(*) as 'total_runs',height,TIMESTAMPDIFF(SECOND, MIN(start_time), MAX(start_time)) / 3600 AS duration_hours, max(start_time) as 'age' from runs where not (height is null\nand exit_run = 1 ) group by 2;\n"
    }
   ]
  }
 ]
}