name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create test secrets file
      run: |
        cp secrets.yml.example secrets.yml
    
    - name: Install dev dependencies
      run: |
        pip install ruff pytest pytest-cov requests-mock redis
        pip install -r components/requirements.txt
        pip install -r celery-services/requirements.txt
    
    - name: Run tests
      run: make test
    
    - name: Clean up secrets
      if: always()
      run: |
        rm -f secrets.yml