name: Deploy to Fly.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [
          { name: "3t-observer-prod", config: "fly.observer.toml" },
          { name: "3t-cors-proxy-prod", config: "fly.proxy.toml" }
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy ${{ matrix.app.name }}
        run: flyctl deploy --remote-only --config ${{ matrix.app.config }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
